/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const showSuccessToast: typeof import('vant/es')['showSuccessToast']
  const showToast: typeof import('vant/es')['showToast']
}
